SELECT * FROM sales.sales;

#WRITE A QUERY TO CALCULATE THE TOTAL SALES(QUANTITY*UNITPRICE) FOR EACH PRODUCT.

Select ProductID,SUM(QUANTITY*UNITPRICE) AS "Total Sales" from sales group by ProductID;

#WRITE A QUERY TO FIND THE TOTAL NUMBER OF PRODUCTS SOLD IN EACH REGION.

Select Region,SUM(QUANTITY) AS "Total Sales" from sales group by Region;

#WRITE A QUERY TO GET THE AVERAGE SALES AMOUNT PER PRODUCT.

Select ProductID,AVG(QUANTITY*UNITPRICE) AS "Average Sales Amount" from sales group by ProductID;

#FIND THE REGIONS WHERE TOTAL SALES ARE MORE THAN 3000.

Select ProductID,SUM(QUANTITY*UNITPRICE) AS "Total Sales" from sales group by ProductID having SUM(QUANTITY*UNITPRICE)>3000;

#WRITE A QUERY TO GET MAXIMUM QUANTITY SOLD FOR EACH PRODUCT.

Select ProductID,MAX(QUANTITY) AS "Maximum Quantity" from sales group by ProductID;

#WRITE A QUERY TO CALCULATE THE AVERAGE QUANTITY OF PRODUCTS SOLD PER REGION.

Select Region,avg(QUANTITY) AS "Average Quantity" from sales group by Region;

#FIND THE PRODUCT IDs THAT HAVE GENERATED A TOTAL SALES AMOUNT OF MORE THAN 1000.

Select ProductID,SUM(QUANTITY*UNITPRICE) AS "Total Sales" from sales group by ProductID having SUM(QUANTITY*UNITPRICE)>1000;

#WRITE A QUERY TO GET THE TOTAL NUMBER OF SALES(ROWS) MADE FOR EACH CUSTOMER. 

Select CustomerID,SUM(QUANTITY*UNITPRICE) AS "Total Sales" from sales group by CustomerID;

#FIND THE PRODUCTS WHICH THE AVERAGE QUANTITY SOLD IS LESS THAN 5. 

Select ProductID,AVG(QUANTITY) AS "Quantity Sold" from Sales group by ProductID having AVG(QUANTITY)<5;

#QUERY TO FIND THE SUM OF TOTAL SALES FOR EACH CUSTOMER IN EACH REGION.

Select CustomerID,SUM(QUANTITY*UNITPRICE) AS "Total Sales" from sales group by CustomerID;

#QUERY TO CALCULATE THE TOTAL SALES FOR EACH MONTH.

Select SalesDate,SUM(QUANTITY*UNITPRICE) AS "Total Sales" from sales group by SalesDate;

#FIND THE REGIONS WHERE THE AVERAGE UNIT PRICE IS MORE THAN 200.

Select Region,AVG(UNITPRICE) from sales group by region having AVG(UNITPRICE)>200;

#QUERY TO GET THE MINIMUM AND MAXIMUM QUANTITY SOLD PER REGION.

Select Region,MAX(QUANTITY) AS "Maximum Quantity Sold",MIN(QUANTITY) AS "Minimum Quantity Sold" from sales group by Region;

#FIND THE CUSTOMERS WHO HAVE MADE MORE THAN 2 PURCHASES.

Select CustomerID, Quantity AS Purchase from sales where Quantity>2;

#QUERY TO FIND THE TOTAL SALES FOR EACH PRODUCT AND FILTER ONLY THOSE PRODUCTS WHERE THE TOTAL SALES EXCEED 1500. 

Select ProductID,SUM(QUANTITY*UNITPRICE) AS "Total Sales" from sales group by ProductID having SUM(QUANTITY*UNITPRICE)>1500;





